version: '3.4'

services:

  redis:
    image: bitnami/redis
    ports:
      - "6379:6379"
    environment: 
      REDIS_PASSWORD: "password123" 

  rabbitmq:
    image: rabbitmq:3.6.5-management
    ports:
      - "5672:5672"
      - "15672:15672" #Management Server
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "password12347"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example  

  api-gateway:
    build:
      context: ./ApiGateway
      dockerfile: ./ApiGateway/Dockerfile
    ports:
      - "55995:80"

  history-service-api:
    build:
      context: ./historyService
      dockerfile: ./HistoryService/Dockerfile
    ports:
      - "61945:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - Database=RecordsDb
      - MongoDBUri=mongodb://root:example@mongo:27017
      - RABBITMQ_URI=amqp://admin:password12347@rabbitmq:5672
    depends_on:
      - rabbitmq
    links:
      - rabbitmq

  predictions-app:
    build:
      context: ./PredictSalariesService
    ports:
      - "5000:80"
    environment:
      RABBITMQ_URI: "amqp://admin:password12347@rabbitmq:5672"
      FLASK_ENV: "Development"
      REDIS_URI: "redis"
      REDIS_PASSWORD: "password123"
      REDIS_PORT: 6379
      REDIS_DB: "0"
    restart: on-failure
    depends_on:
      - "rabbitmq"
 
  load-test:
    image:  locustio/locust
    environment:
      TARGET_URL: http://predictions-app_1:80
      LOCUSTFILE_PATH:  /mnt/locust/locustfile.py
    ports:
      - "8089:8089"
    volumes:
      - ./load_test:/mnt/locust

  ws-server:
    build:
      context: ./ws
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"

  worker:
    build:
      context: ./workerService
      dockerfile: ./Dockerfile

  spa-client:
    build:
      context: ./spaClient
      dockerfile: ./Dockerfile
    ports:
      - "8888:80"  
   