version: '3.4'

services:

  redis:
    image: bitnami/redis
    ports:
      - "6379:6379"
    environment: 
      REDIS_PASSWORD: "password123" 

  rabbitmq:
    image: rabbitmq:3.6.5-management
    ports:
      - "5672:5672"
      - "15672:15672" #Management Server
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "password12347"
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"

    healthcheck:
      test: ["CMD", "curl", "-f", "http://rabbitmq:15672"]
      interval: 30s
      timeout: 10s
      retries: 5   

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example  

  history-service-api:
    ports:
      - "61945:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - Database=RecordsDb
      - MongoDBUri=mongodb://root:example@mongo:27017
      - RABBITMQ_URI=amqp://admin:password12347@rabbitmq:5672
      - CORS=http://localhost:8888
      - redis:connection=redis
      - redis:password=password123
      - redis:port=6379
      - redis:channel=ws:messages
    depends_on:
      - rabbitmq
    links:
      - rabbitmq

  predictions-app:
    ports:
      - "5000:80"
    environment:
      RABBITMQ_URI: "amqp://admin:password12347@rabbitmq:5672"
      FLASK_ENV: "Production"
      REDIS_URI: "redis"
      REDIS_PASSWORD: "password123"
      REDIS_PORT: 6379
      REDIS_DB: "0"
      CORS: "http://localhost:8888"
    restart: on-failure
    depends_on:
      - "rabbitmq"
  
  ws-server:
    ports:
      - "8080:8080"
    environment:
      redis_uri: "redis"
      redis_password: "password123"
      redis_port: 6379
      redis_channel: "ws:messages"
    depends_on:
      - "redis"

  spa-client:
    ports:
      - "8888:80"
