version: '3.4'

services:

  redis:
    image: bitnami/redis
    ports:
      - "6379:6379"
    environment: 
      REDIS_PASSWORD: "password123" 
  
  rabbitmq:
    image: rabbitmq:3.6.5-management
    ports:
      - "5672:5672"
      - "15672:15672" #Management Server
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "password12347"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example  
  
  history-service-api:
    image: cealer/history-service-app
    ports:
      - "61945:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - Database=RecordsDb
      - MongoDBUri=mongodb://root:example@mongo:27017
      - RABBITMQ_URI=amqp://admin:password12347@rabbitmq:5672
      - CORS=*
      - redis:connection=redis
      - redis:password=password123
      - redis:port=6379
      - redis:channel=ws:messages
    depends_on:
      - rabbitmq
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://rabbitmq:15672"]
      interval: 30s
      timeout: 10s
      retries: 5

  predictions-app:
    image: cealer/prediction-salary-service
    ports:
      - "5000:80"
    environment:
      RABBITMQ_URI: "amqp://admin:password12347@rabbitmq:5672"
      FLASK_ENV: "Production"
      REDIS_URI: "redis"
      REDIS_PASSWORD: "password123"
      REDIS_PORT: 6379
      REDIS_DB: "0"
      CORS: "*"
    depends_on:
      - "rabbitmq"

  ws-server:
    image: "cealer/ws-server"
    ports:
      - "8080:8080"
    environment:
      redis_uri: "redis"
      redis_password: "password123"
      redis_port: 6379
      redis_channel: "ws:messages"

  spa-client:
    image: "cealer/spa-client"
    ports:
      - "8888:80"
    environment:
      - API_GATEWAY=http://localhost:9090
      - GATEWAY_HOST=localhost:9090

  api-gateway:
    ports:
      - "9090:80"