### STAGE 1: Build ###
FROM node:12.7-alpine AS build
WORKDIR /src/app
COPY package.json ./
RUN npm install
COPY . .
RUN npm run build:prod
### STAGE 2: Run ###
FROM nginx:stable-alpine
COPY --from=build /src/app/dist/spaClient /usr/share/nginx/html
CMD ["/bin/sh",  "-c",  "envsubst < /usr/share/nginx/html/assets/env.template.js > /usr/share/nginx/html/assets/env.js && exec nginx -g 'daemon off;'"]
